local M = {}
M.dracula = {
    name           = "dracula",

    cyan           = "#8be9fd",
    green          = "#50fa7b",
    orange         = "#ffb86c",
    red            = "#ff5555",
    pink           = "#ff79c6",
    magenta        = "#c678dd",
    yellow         = "#f1fa8c",
    aqua           = "#3affdb",
    beige          = "#f5c06f",
    brown          = "#905532",
    blue           = "#5fd7ff",
    salmon         = "#ee6e73",
    violet         = "#bd93f9",
    purple         = "#a9a1e1",
    paleblue       = "#6272a4",
    white          = "#eff0f1",
    black          = "#1b1f2a",
    grey           = "#44475A",
    grey1          = "#4B5263",

    bright_red     = "#FF6E6E",
    bright_green   = "#69FF94",
    bright_yellow  = "#FFFFA5",
    bright_violet  = "#D6ACFF",
    bright_magenta = "#FF92DF",
    bright_cyan    = "#A4FFFF",
    bright_blue    = "#4ff7ff",
    bright_white   = "#FFFFFF",
    bright_black   = "#21222C",
    bright_grey    = "#8c979a",
    bright_grey1   = "#7f7f7f",

    dark_red        = '#ff6666',
    dark_green      = '#31b53e',
    dark_yellow     = '#d1da6c',
    dark_blue       = "#51afef",
    dark_cyan       = '#71c6e7',
    dark_purple     = '#b480d6',
    dark_orange     = "#d4843e",
    dark_pink       = "#834f79",
    dark_violet     = "#9f7fdf",
    dark_white      = "#cfcfcf",
    dark_black      = "#181a26",
    dark_grey       = "#282a36",
    dark_grey1      = "#3E4452",
}
return M
