timezones="
CI, BF, GH, GM, GN, ML, MR, SH, SL, SN, TG___Africa/Abidjan
GH___Africa/Accra
ET___Africa/Addis_Ababa
DZ___Africa/Algiers
ER___Africa/Asmara
ER___Africa/Asmera
ML___Africa/Bamako
CF___Africa/Bangui
GM___Africa/Banjul
GW___Africa/Bissau
MW___Africa/Blantyre
CG___Africa/Brazzaville
BI___Africa/Bujumbura
EG___Africa/Cairo
MA___Africa/Casablanca
ES___Africa/Ceuta
GN___Africa/Conakry
SN___Africa/Dakar
TZ___Africa/Dar_es_Salaam
DJ___Africa/Djibouti
CM___Africa/Douala
EH___Africa/El_Aaiun
SL___Africa/Freetown
BW___Africa/Gaborone
ZW___Africa/Harare
ZA, LS, SZ___Africa/Johannesburg
SS___Africa/Juba
UG___Africa/Kampala
SD___Africa/Khartoum
RW___Africa/Kigali
CD___Africa/Kinshasa
NG, AO, BJ, CD, CF, CG, CM, GA, GQ, NE___Africa/Lagos
GA___Africa/Libreville
TG___Africa/Lome
AO___Africa/Luanda
CD___Africa/Lubumbashi
ZM___Africa/Lusaka
GQ___Africa/Malabo
MZ, BI, BW, CD, MW, RW, ZM, ZW___Africa/Maputo
LS___Africa/Maseru
SZ___Africa/Mbabane
SO___Africa/Mogadishu
LR___Africa/Monrovia
KE, DJ, ER, ET, KM, MG, SO, TZ, UG, YT___Africa/Nairobi
TD___Africa/Ndjamena
NE___Africa/Niamey
MR___Africa/Nouakchott
BF___Africa/Ouagadougou
BJ___Africa/Porto-Novo
ST___Africa/Sao_Tome
ML___Africa/Timbuktu
LY___Africa/Tripoli
TN___Africa/Tunis
NA___Africa/Windhoek
US___America/Adak
US___America/Anchorage
AI___America/Anguilla
AG___America/Antigua
BR___America/Araguaina
AR___America/Argentina/Buenos_Aires
AR___America/Argentina/Catamarca
AR___America/Argentina/ComodRivadavia
AR___America/Argentina/Cordoba
AR___America/Argentina/Jujuy
AR___America/Argentina/La_Rioja
AR___America/Argentina/Mendoza
AR___America/Argentina/Rio_Gallegos
AR___America/Argentina/Salta
AR___America/Argentina/San_Juan
AR___America/Argentina/San_Luis
AR___America/Argentina/Tucuman
AR___America/Argentina/Ushuaia
AW___America/Aruba
PY___America/Asuncion
CA___America/Atikokan
US___America/Atka
BR___America/Bahia
MX___America/Bahia_Banderas
BB___America/Barbados
BR___America/Belem
BZ___America/Belize
CA___America/Blanc-Sablon
BR___America/Boa_Vista
CO___America/Bogota
US___America/Boise
AR___America/Buenos_Aires
CA___America/Cambridge_Bay
BR___America/Campo_Grande
MX___America/Cancun
VE___America/Caracas
AR___America/Catamarca
GF___America/Cayenne
KY___America/Cayman
US___America/Chicago
MX___America/Chihuahua
CA___America/Coral_Harbour
AR___America/Cordoba
CR___America/Costa_Rica
CA___America/Creston
BR___America/Cuiaba
CW___America/Curacao
GL___America/Danmarkshavn
CA___America/Dawson
CA___America/Dawson_Creek
US___America/Denver
US___America/Detroit
DM___America/Dominica
CA___America/Edmonton
BR___America/Eirunepe
SV___America/El_Salvador
MX___America/Ensenada
CA___America/Fort_Nelson
US___America/Fort_Wayne
BR___America/Fortaleza
CA___America/Glace_Bay
GL___America/Godthab
CA___America/Goose_Bay
TC___America/Grand_Turk
GD___America/Grenada
GP___America/Guadeloupe
GT___America/Guatemala
EC___America/Guayaquil
GY___America/Guyana
CA___America/Halifax
CU___America/Havana
MX___America/Hermosillo
US___America/Indiana/Indianapolis
US___America/Indiana/Knox
US___America/Indiana/Marengo
US___America/Indiana/Petersburg
US___America/Indiana/Tell_City
US___America/Indiana/Vevay
US___America/Indiana/Vincennes
US___America/Indiana/Winamac
US___America/Indianapolis
CA___America/Inuvik
CA___America/Iqaluit
JM___America/Jamaica
AR___America/Jujuy
US___America/Juneau
US___America/Kentucky/Louisville
US___America/Kentucky/Monticello
US___America/Knox_IN
BQ___America/Kralendijk
BO___America/La_Paz
PE___America/Lima
US___America/Los_Angeles
US___America/Louisville
SX___America/Lower_Princes
BR___America/Maceio
NI___America/Managua
BR___America/Manaus
MF___America/Marigot
MQ___America/Martinique
MX___America/Matamoros
MX___America/Mazatlan
AR___America/Mendoza
US___America/Menominee
MX___America/Merida
US___America/Metlakatla
MX___America/Mexico_City
PM___America/Miquelon
CA___America/Moncton
MX___America/Monterrey
UY___America/Montevideo
CA___America/Montreal
MS___America/Montserrat
BS___America/Nassau
US___America/New_York
CA___America/Nipigon
US___America/Nome
BR___America/Noronha
US___America/North_Dakota/Beulah
US___America/North_Dakota/Center
US___America/North_Dakota/New_Salem
GL___America/Nuuk
MX___America/Ojinaga
PA, CA, KY___America/Panama
CA___America/Pangnirtung
SR___America/Paramaribo
US, CA___America/Phoenix
HT___America/Port-au-Prince
TT___America/Port_of_Spain
BR___America/Porto_Acre
BR___America/Porto_Velho
PR, AG, CA, AI, AW, BL, BQ, CW, DM, GD, GP, KN, LC, MF, MS, SX, TT, VC, VG, VI___America/Puerto_Rico
CL___America/Punta_Arenas
CA___America/Rainy_River
CA___America/Rankin_Inlet
BR___America/Recife
CA___America/Regina
CA___America/Resolute
BR___America/Rio_Branco
AR___America/Rosario
MX___America/Santa_Isabel
BR___America/Santarem
CL___America/Santiago
DO___America/Santo_Domingo
BR___America/Sao_Paulo
GL___America/Scoresbysund
US___America/Shiprock
US___America/Sitka
BL___America/St_Barthelemy
CA___America/St_Johns
KN___America/St_Kitts
LC___America/St_Lucia
VI___America/St_Thomas
VC___America/St_Vincent
CA___America/Swift_Current
HN___America/Tegucigalpa
GL___America/Thule
CA___America/Thunder_Bay
MX___America/Tijuana
CA, BS___America/Toronto
VG___America/Tortola
CA___America/Vancouver
VI___America/Virgin
CA___America/Whitehorse
CA___America/Winnipeg
US___America/Yakutat
CA___America/Yellowknife
AQ___Antarctica/Casey
AQ___Antarctica/Davis
AQ___Antarctica/DumontDUrville
AU___Antarctica/Macquarie
AQ___Antarctica/Mawson
AQ___Antarctica/McMurdo
AQ___Antarctica/Palmer
AQ___Antarctica/Rothera
AQ___Antarctica/South_Pole
AQ___Antarctica/Syowa
AQ___Antarctica/Troll
AQ___Antarctica/Vostok
SJ___Arctic/Longyearbyen
YE___Asia/Aden
KZ___Asia/Almaty
JO___Asia/Amman
RU___Asia/Anadyr
KZ___Asia/Aqtau
KZ___Asia/Aqtobe
TM___Asia/Ashgabat
TM___Asia/Ashkhabad
KZ___Asia/Atyrau
IQ___Asia/Baghdad
BH___Asia/Bahrain
AZ___Asia/Baku
TH, KH, LA, VN___Asia/Bangkok
RU___Asia/Barnaul
LB___Asia/Beirut
KG___Asia/Bishkek
BN___Asia/Brunei
IN___Asia/Calcutta
RU___Asia/Chita
MN___Asia/Choibalsan
CN___Asia/Chongqing
CN___Asia/Chungking
LK___Asia/Colombo
BD___Asia/Dacca
SY___Asia/Damascus
BD___Asia/Dhaka
TL___Asia/Dili
AE, OM___Asia/Dubai
TJ___Asia/Dushanbe
CY___Asia/Famagusta
PS___Asia/Gaza
CN___Asia/Harbin
PS___Asia/Hebron
VN___Asia/Ho_Chi_Minh
HK___Asia/Hong_Kong
MN___Asia/Hovd
RU___Asia/Irkutsk
TR___Asia/Istanbul
ID___Asia/Jakarta
ID___Asia/Jayapura
IL___Asia/Jerusalem
AF___Asia/Kabul
RU___Asia/Kamchatka
PK___Asia/Karachi
CN___Asia/Kashgar
NP___Asia/Kathmandu
NP___Asia/Katmandu
RU___Asia/Khandyga
IN___Asia/Kolkata
RU___Asia/Krasnoyarsk
MY___Asia/Kuala_Lumpur
MY___Asia/Kuching
KW___Asia/Kuwait
MO___Asia/Macao
MO___Asia/Macau
RU___Asia/Magadan
ID___Asia/Makassar
PH___Asia/Manila
OM___Asia/Muscat
CY___Asia/Nicosia
RU___Asia/Novokuznetsk
RU___Asia/Novosibirsk
RU___Asia/Omsk
KZ___Asia/Oral
KH___Asia/Phnom_Penh
ID___Asia/Pontianak
KP___Asia/Pyongyang
QA, BH___Asia/Qatar
KZ___Asia/Qostanay
KZ___Asia/Qyzylorda
MM___Asia/Rangoon
SA, AQ, KW, YE___Asia/Riyadh
VN___Asia/Saigon
RU___Asia/Sakhalin
UZ___Asia/Samarkand
KR___Asia/Seoul
CN___Asia/Shanghai
SG, MY___Asia/Singapore
RU___Asia/Srednekolymsk
TW___Asia/Taipei
UZ___Asia/Tashkent
GE___Asia/Tbilisi
IR___Asia/Tehran
IL___Asia/Tel_Aviv
BT___Asia/Thimbu
BT___Asia/Thimphu
JP___Asia/Tokyo
RU___Asia/Tomsk
ID___Asia/Ujung_Pandang
MN___Asia/Ulaanbaatar
MN___Asia/Ulan_Bator
CN___Asia/Urumqi
RU___Asia/Ust-Nera
LA___Asia/Vientiane
RU___Asia/Vladivostok
RU___Asia/Yakutsk
MM___Asia/Yangon
RU___Asia/Yekaterinburg
AM___Asia/Yerevan
PT___Atlantic/Azores
BM___Atlantic/Bermuda
ES___Atlantic/Canary
CV___Atlantic/Cape_Verde
FO___Atlantic/Faeroe
FO___Atlantic/Faroe
SJ___Atlantic/Jan_Mayen
PT___Atlantic/Madeira
IS___Atlantic/Reykjavik
GS___Atlantic/South_Georgia
SH___Atlantic/St_Helena
FK___Atlantic/Stanley
AU___Australia/ACT
AU___Australia/Adelaide
AU___Australia/Brisbane
AU___Australia/Broken_Hill
AU___Australia/Canberra
AU___Australia/Currie
AU___Australia/Darwin
AU___Australia/Eucla
AU___Australia/Hobart
AU___Australia/LHI
AU___Australia/Lindeman
AU___Australia/Lord_Howe
AU___Australia/Melbourne
AU___Australia/North
AU___Australia/NSW
AU___Australia/Perth
AU___Australia/Queensland
AU___Australia/South
AU___Australia/Sydney
AU___Australia/Tasmania
AU___Australia/Victoria
AU___Australia/West
AU___Australia/Yancowinna
BR___Brazil/Acre
BR___Brazil/DeNoronha
BR___Brazil/East
BR___Brazil/West
CA___Canada/Atlantic
CA___Canada/Central
CA___Canada/Eastern
CA___Canada/Mountain
CA___Canada/Newfoundland
CA___Canada/Pacific
CA___Canada/Saskatchewan
CA___Canada/Yukon
___CET
CL___Chile/Continental
CL___Chile/EasterIsland
___CST6CDT
CU___Cuba
___EET
EG___Egypt
IE___Eire
___EST
___EST5EDT
___Etc/GMT
___Etc/GMT+0
___Etc/GMT+1
___Etc/GMT+10
___Etc/GMT+11
___Etc/GMT+12
___Etc/GMT+2
___Etc/GMT+3
___Etc/GMT+4
___Etc/GMT+5
___Etc/GMT+6
___Etc/GMT+7
___Etc/GMT+8
___Etc/GMT+9
___Etc/GMT-0
___Etc/GMT-1
___Etc/GMT-10
___Etc/GMT-11
___Etc/GMT-12
___Etc/GMT-13
___Etc/GMT-14
___Etc/GMT-2
___Etc/GMT-3
___Etc/GMT-4
___Etc/GMT-5
___Etc/GMT-6
___Etc/GMT-7
___Etc/GMT-8
___Etc/GMT-9
___Etc/GMT0
___Etc/Greenwich
___Etc/UCT
___Etc/Universal
___Etc/UTC
___Etc/Zulu
NL___Europe/Amsterdam
AD___Europe/Andorra
RU___Europe/Astrakhan
GR___Europe/Athens
GB___Europe/Belfast
RS, BA, HR, ME, MK, SI___Europe/Belgrade
DE___Europe/Berlin
SK___Europe/Bratislava
BE___Europe/Brussels
RO___Europe/Bucharest
HU___Europe/Budapest
DE___Europe/Busingen
MD___Europe/Chisinau
DK___Europe/Copenhagen
IE___Europe/Dublin
GI___Europe/Gibraltar
GG___Europe/Guernsey
FI, AX___Europe/Helsinki
IM___Europe/Isle_of_Man
TR___Europe/Istanbul
JE___Europe/Jersey
RU___Europe/Kaliningrad
UA___Europe/Kiev
RU___Europe/Kirov
PT___Europe/Lisbon
SI___Europe/Ljubljana
GB, GG, IM, JE___Europe/London
LU___Europe/Luxembourg
ES___Europe/Madrid
MT___Europe/Malta
AX___Europe/Mariehamn
BY___Europe/Minsk
MC___Europe/Monaco
RU___Europe/Moscow
CY___Europe/Nicosia
NO, SJ___Europe/Oslo
FR___Europe/Paris
ME___Europe/Podgorica
CZ, SK___Europe/Prague
LV___Europe/Riga
IT, SM, VA___Europe/Rome
RU___Europe/Samara
SM___Europe/San_Marino
BA___Europe/Sarajevo
RU___Europe/Saratov
RU, UA___Europe/Simferopol
MK___Europe/Skopje
BG___Europe/Sofia
SE___Europe/Stockholm
EE___Europe/Tallinn
AL___Europe/Tirane
MD___Europe/Tiraspol
RU___Europe/Ulyanovsk
UA___Europe/Uzhgorod
LI___Europe/Vaduz
VA___Europe/Vatican
AT___Europe/Vienna
LT___Europe/Vilnius
RU___Europe/Volgograd
PL___Europe/Warsaw
HR___Europe/Zagreb
UA___Europe/Zaporozhye
CH, DE, LI___Europe/Zurich
___Factory
GB___GB
GB___GB-Eire
___GMT
___GMT+0
___GMT-0
___GMT0
___Greenwich
HK___Hongkong
___HST
IS___Iceland
MG___Indian/Antananarivo
IO___Indian/Chagos
CX___Indian/Christmas
CC___Indian/Cocos
KM___Indian/Comoro
TF___Indian/Kerguelen
SC___Indian/Mahe
MV___Indian/Maldives
MU___Indian/Mauritius
YT___Indian/Mayotte
RE, TF___Indian/Reunion
IR___Iran
IL___Israel
JM___Jamaica
JP___Japan
MH___Kwajalein
LY___Libya
___MET
MX___Mexico/BajaNorte
MX___Mexico/BajaSur
MX___Mexico/General
___MST
___MST7MDT
US___Navajo
NZ___NZ
NZ___NZ-CHAT
WS___Pacific/Apia
NZ, AQ___Pacific/Auckland
PG___Pacific/Bougainville
NZ___Pacific/Chatham
FM___Pacific/Chuuk
CL___Pacific/Easter
VU___Pacific/Efate
KI___Pacific/Enderbury
TK___Pacific/Fakaofo
FJ___Pacific/Fiji
TV___Pacific/Funafuti
EC___Pacific/Galapagos
PF___Pacific/Gambier
SB___Pacific/Guadalcanal
GU, MP___Pacific/Guam
US, UM___Pacific/Honolulu
UM___Pacific/Johnston
KI___Pacific/Kanton
KI___Pacific/Kiritimati
FM___Pacific/Kosrae
MH___Pacific/Kwajalein
MH___Pacific/Majuro
PF___Pacific/Marquesas
UM___Pacific/Midway
NR___Pacific/Nauru
NU___Pacific/Niue
NF___Pacific/Norfolk
NC___Pacific/Noumea
AS, UM___Pacific/Pago_Pago
PW___Pacific/Palau
PN___Pacific/Pitcairn
FM___Pacific/Pohnpei
FM___Pacific/Ponape
PG, AQ___Pacific/Port_Moresby
CK___Pacific/Rarotonga
MP___Pacific/Saipan
WS___Pacific/Samoa
PF___Pacific/Tahiti
KI___Pacific/Tarawa
TO___Pacific/Tongatapu
FM___Pacific/Truk
UM___Pacific/Wake
WF___Pacific/Wallis
FM___Pacific/Yap
PL___Poland
PT___Portugal
CN___PRC
___PST8PDT
TW___ROC
KR___ROK
SG___Singapore
TR___Turkey
___UCT
___Universal
US___US/Alaska
US___US/Aleutian
US___US/Arizona
US___US/Central
US___US/East-Indiana
US___US/Eastern
US___US/Hawaii
US___US/Indiana-Starke
US___US/Michigan
US___US/Mountain
US___US/Pacific
WS___US/Samoa
___UTC
RU___W-SU
___WET
___Zulu
"
##BH |worldclock|live search zones and get time of any time zone|
worldclock ()
{
    timezone=$(printf "$timezones" | awk 'BEGIN{FS="___"}{print $1 "\t" $2}' | fzf)
    timezone=$(echo $timezone | awk '{print $2}')
    echo -ne "$timezone time is  :  "
    env TZ=$timezone date
}

##BH |worldclockshow|show times at different zones|
worldclockshow ()
{
    local timezs="
    IN___Asia/Kolkata
    AU___Australia/Melbourne
    RO___Europe/Bucharest
    US___US/Pacific
    US___US/Central
    "
    for i in $timezs
    do
        timezone=$(printf "$i" | awk 'BEGIN{FS="___"}{print $1 "\t" $2}')
        timezone=$(echo $timezone | awk '{print $2}')
        echo -ne "$timezone time is  :  \n\t"
        env TZ=$timezone date
        echo -ne "\n"
    done
}
##BH |swc|show times at different zones|
alias swc='worldclockshow'
##BH |fwc|live search zones and get time of any time zone|
alias fwc='worldclock'
